name: math_go
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.1.6
  firebase_core: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter_map: ^0.14.0
  location: ^4.3.0
  firebase_auth: ^3.3.16
  google_sign_in: ^5.3.0
  flutter_compass: ^0.7.0
  firebase_database: ^9.0.12
  animated_text_kit: ^4.2.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  background_image: assets/images/logos_and_icons/background.png
  image: assets/images/logos_and_icons/logo.png

flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/beasties/
    - assets/images/logos_and_icons/
    - assets/.env
  uses-material-design: true

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HoltwoodOneSC
      fonts:
        - asset: assets/fonts/HoltwoodOneSC-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
